INSERT INTO PEOPLE (Name,Surname_1,Surname_2,Address,Town,Dni,Mobile,Email,Birth)
  (SELECT NOMBRE_DUENO,APELL_1_DUENO,APELL_2_DUENO,DIRECC_DUENO,CIUDAD_DUENO,NIF_DUENO,TO_NUMBER(TLF_DUENO,'999999999'),EMAIL_DUENO,TO_DATE(CUMPLE_DUENO,'YYYY-MM-DD')
    FROM FSDB.MEGATABLE
    UNION
  SELECT NOMBRE_CONDTR,APELL_1_CONDTR,APELL_2_CONDTR,DIRECC_CONDTR,CIUDAD_CONDTR,NIF_CONDTR,TO_NUMBER(TLF_CONDTR,'999999999'),EMAIL_CONDTR,TO_DATE(CUMPLE_CONDTR,'YYYY-MM-DD')
    FROM FSDB.MEGATABLE);
/*
  197 owners
  207 drivers
  from which 100 are both roles

  248 ROWS CREATED
*/

INSERT INTO DRIVER (DriverDni,type,ldate,age)
  SELECT DISTINCT NIF_CONDTR,CARNET_CONDTR,TO_DATE(FECHA_CARNET,'YYYY-MM-DD'),EDAD_CONDTR
    FROM FSDB.MEGATABLE WHERE EDAD_CONDTR >= 18;
/*
  203 ROWS CREATED
*/

INSERT INTO VEHICLE (nPlate,VIN,registration,brand,model,color,itv,Dni)
  SELECT DISTINCT MATRICULA,VIN,TO_DATE(FECHA_MATRICULA,'YYYY/MM/DD'),MARCA,MODELO,COLOR,TO_DATE(FECHA_ITV,'YYYY/MM/DD'),NIF_DUENO
    FROM FSDB.MEGATABLE;
/*
  250 ROWS CREATED
*/
