/*	SELECT COUNT(*) FROM (((
		SELECT DISTINCT NIF_DUENO
			FROM FSDB.MEGATABLE
			WHERE NOT NIF_DUENO = NIF_CONDTR)
  --97 owners who do not drive
   UNION
  (SELECT DISTINCT NIF_CONDTR
			FROM FSDB.MEGATABLE
			WHERE NOT NIF_DUENO = NIF_CONDTR))
  --107 drivers which are not owners
	UNION
  (SELECT NIF_DUENO
    FROM FSDB.MEGATABLE
    INTERSECT
  SELECT NIF_CONDTR
    FROM FSDB.MEGATABLE));
	--156 are both roles
*/

INSERT INTO PEOPLE (Name,Surname_1,Surname_2,Address,Town,Dni,Mobile,Email,Birth)
  (SELECT NOMBRE_DUENO,APELL_1_DUENO,APELL_2_DUENO,DIRECC_DUENO,CIUDAD_DUENO,NIF_DUENO,TO_NUMBER(TLF_DUENO,'999999999'),EMAIL_DUENO,TO_DATE(CUMPLE_DUENO,'YYYY-MM-DD')
    FROM FSDB.MEGATABLE
    UNION
  SELECT NOMBRE_CONDTR,APELL_1_CONDTR,APELL_2_CONDTR,DIRECC_CONDTR,CIUDAD_CONDTR,NIF_CONDTR,TO_NUMBER(TLF_CONDTR,'999999999'),EMAIL_CONDTR,TO_DATE(CUMPLE_CONDTR,'YYYY-MM-DD')
    FROM FSDB.MEGATABLE);
/*
  248 ROWS CREATED
*/

INSERT INTO DRIVER (DriverDni,type,ldate)
  SELECT DISTINCT NIF_CONDTR,CARNET_CONDTR,TO_DATE(FECHA_CARNET,'YYYY-MM-DD')
    FROM FSDB.MEGATABLE WHERE EDAD_CONDTR >= 18;
/*
  203 ROWS CREATED
*/

INSERT INTO POWER_VEHICLE (brand, model, power)
SELECT MARCA, MODELO, min(POTENCIA)
FROM FSDB.MEGATABLE GROUP BY MARCA, MODELO;
/*
  32 ROWS CREATED
*/

INSERT INTO VEHICLE (nPlate,VIN,registration,color,brand,model,itv,Dni)
SELECT DISTINCT MATRICULA,VIN,TO_DATE(FECHA_MATRICULA,'YYYY-MM-DD'),COLOR,MARCA,MODELO,TO_DATE(FECHA_ITV,'YYYY-MM-DD'),NIF_DUENO
FROM FSDB.MEGATABLE;
/*
  250 ROWS CREATED
*/

INSERT INTO DRIVES_VEHICLE (DriverDni,nPlate)
SELECT DISTINCT NIF_CONDTR, MATRICULA
FROM FSDB.MEGATABLE WHERE EDAD_CONDTR >= 18;
/*
  246 ROWS CREATED
*/

INSERT INTO ROAD (rname, speedlimit)
SELECT DISTINCT CARRETERA_FOTO, LIMIT_VEL_CTERA
FROM FSDB.MEGATABLE;
/*
  10 ROWS CREATED
*/

INSERT INTO RADAR (rname, mileagepoint, direction, speedlimit)
SELECT DISTINCT CARRETERA_FOTO, PTO_KM_RADAR, SENTIDO_RADAR, MIN(LIMIT_VEL_RADAR)
FROM FSDB.MEGATABLE GROUP BY CARRETERA_FOTO,PTO_KM_RADAR,SENTIDO_RADAR;
/*
  150 ROWS CREATED
*/

INSERT INTO OBSERVATION (odate, otime, speed, rname, mileagepoint, direction, nPlate)
SELECT DISTINCT TO_DATE(FECHA_FOTO, 'YYYY-MM-DD'), TO_TIMESTAMP(HORA_FOTO, 'HH24:MI:SS.FF'), VELOCIDAD_FOTO, CARRETERA_FOTO, PTO_KM_RADAR, SENTIDO_RADAR, MATRICULA
FROM FSDB.MEGATABLE;
/*
  50000 ROWS CREATED
*/
