INSERT INTO OWNER (Name,Surname_1,Surname_2,Address,Town,Dni,Mobile,Email,Birth)
  SELECT DISTINCT NOMBRE_DUENO,APELL_1_DUENO,APELL_2_DUENO,DIRECC_DUENO,CIUDAD_DUENO,NIF_DUENO,TO_NUMBER(TLF_DUENO,'999999999'),EMAIL_DUENO,TO_DATE(CUMPLE_DUENO,'YYYY-MM-DD')
    FROM FSDB.MEGATABLE;
/*197 FILAS*/

INSERT INTO DRIVER (Dni,type,ldate,age)
  SELECT NIF_DUENO,CARNET_CONDTR,TO_DATE(FECHA_CARNET,'YYYY-MM-DD'),EDAD_CONDTR
    FROM FSDB.MEGATABLE;
